### ISSUE TITLE
Future of draw2d

### ISSUE THREAD

**Issue by Sakerdotes** [freegroup/draw2d#1]
### Information
I am using draw2d with npm at the moment (was a bit tricky) and altered/fixed much in the source code to make it fit right to my requirements. So I am curious if it could be usefull in my case to switch to this version of draw2d in the future. 

### Question
Has draw2d just made compatible with npm/yarn or will it get more updates/fixes in the future?

**Comment by freegroup** [comment]
during the migration to yarn/npm/webpack I found several bugs within the lib. This
fixes are done in this lib only and didn't go back into the original lib. The old lib
stays still alive and fixes come in if any customer reports me a problem.

regarding your question - not just compatible to npm...fixes and enhancements are part of the lib.

I migrate my personal project https://github.com/freegroup/brainbox to the new version and it is working well. Migration to webpack and npm takes 1 week and I'm very happy that I did it.

BUT - using webpack and draw2d isn't perfect. If you need to read JSON models you must
use draw2d as a global object. just **import draw2d from "draw2d"** didn't work. In this
case, the closure is not your friend.
 
last but not least: draw2d isn't dead. This repo is the future for further enhancments.

**Comment by pa-solution2020** [comment]
Hi, @freegroup
Would you like to let me know how can you use draw2d globally in React.js TypeScript?
