### ISSUE TITLE
Allow connections only between certain kinds of nodes.

### ISSUE THREAD

**Issue by mattecapu** [freegroup/draw2d#100]
Hello,
I'm drawing Petri nets using Draw2D. A PN is like a graph, where some nodes are called 'places' and others 'transitions', but you don't have edges going directly from a place to another place, or between two transitions. To go from a place to another, you have to pass from a transition.
Is there a way to allow connections starting at an inputport to only end in some outputports?

BTW the library is great, thanks for your work!

**Comment by kogaba** [comment]
I think you are looking for this:
https://freegroup.github.io/draw2d/index.html#/examples/port_semantic_group
