### ISSUE TITLE
Strange behavior when scrolling the canvas

### ISSUE THREAD

**Issue by e2sence** [freegroup/draw2d#101]
good day, strange behavior when scrolling the canvas
this is how it looks:
![ezgif-6-7542a56b0ccb](https://user-images.githubusercontent.com/32023734/79039444-f8346080-7be9-11ea-9446-f0687dd1011a.gif)
Any ideas how to fix this?

**Comment by freegroup** [comment]
this is because Draw2D is unable to determine which part of or UI is the scrolling area.
You can set it or calculate the offset by yourself. see
https://github.com/freegroup/draw2d/issues/44#issuecomment-521706009

**Comment by e2sence** [comment]
thanks [#44 (comment)](https://github.com/freegroup/draw2d/issues/44#issuecomment-521706009) helped me, final code looks like this:

fromDocumentToCanvasCoordinate: function(x, y) {
        var x1 = $("html").scrollLeft()
        var y1 = $("html").scrollTop()
        return new draw2d.geo.Point(
            (x + x1 - this.getAbsoluteX()) * this.zoomFactor,
            (y + y1 - this.getAbsoluteY()) * this.zoomFactor)
    }

**Comment by freegroup** [comment]
hi

this is the default implementation. You can just use `canvas.setScrollArea("html")` and it should work out of the box.
