### ISSUE TITLE
Could draw2d create interactive mindmap?

### ISSUE THREAD

**Issue by greenTea2Codes** [freegroup/draw2d#102]
Hi, 

I am searching for our angular 6 project a visualization library for creating interactive mind map. Draw2d seems to have a good documentation about the API but I could not find if it supports collapsing and expanding child nodes. Could someone let me know which API would support collapsing and expanding child nodes?

Thank you!

**Comment by freegroup** [comment]
Hi,

draw2d isn'T a good candidate for a mind map software. The main purpose of draw2d is to draw lines between ports and shapes. For a mind map you need layout capabilities and automatic connection creations.

sorry

Andreas
