### ISSUE TITLE
Best practice for the implementation of highly loaded projects

### ISSUE THREAD

**Issue by e2sence** [freegroup/draw2d#104]
Best practice for the implementation of highly loaded projects. 
There is a figure that uses JAIL with a text heading.
<img width="1548" alt="Screenshot 2020-04-19 at 19 11 59" src="https://user-images.githubusercontent.com/32023734/79693158-bd799a80-8271-11ea-91df-d46ff0632cd6.png">

because There is no ready implementation supporting folding, I have to recreate objects every time I open them and recount the coordinates. This is very stressful for the system.
maybe there are considerations how to speed up the implementation?

**Comment by freegroup** [comment]
Hi,

there is no need to rebuild all the figures during expand/collapse. You can just hide them
https://codepen.io/freegroup/pen/QWjEXJK

**Comment by freegroup** [comment]
```javascript
// Generated Code for the Draw2D touch HTML5 lib
//
// http://www.draw2d.org
//
// Tue Mar 29 2016 19:19:12 GMT+0200 (CEST)                                         
//
// Go to the Designer http://www.draw2d.org
// to design your own shape or download user generated
//
let CollapsibleJailhouse = draw2d.shape.composite.Jailhouse.extend({

  NAME: "CollapsibleJailhouse",

  init: function (attr, setter, getter) {
    this._super($.extend({stroke: 0, bgColor: "#ff0000", width: 270, height: 184}, attr), setter, getter);

    this.expanded = true;
    this.collapsedWidth  = 90
    this.collapsedHeight = 20

    let absoluteLocator = new draw2d.layout.locator.XYAbsPortLocator({x:0, y:0})

    let img1 = new draw2d.shape.icon.Contract({minWidth: 20, minHeight: 20, width: 20, height: 20});
    let img2 = new draw2d.shape.icon.Expand({minWidth: 20, minHeight: 20, width: 20, height: 20, visible: false});

    this.add(img1, absoluteLocator)
    this.add(img2, absoluteLocator)

    let toggle=()=>{
      this.expanded = !this.expanded

      img1.setVisible( this.expanded)
      img2.setVisible(!this.expanded)

      if(this.expanded){
        this.installEditPolicy(new draw2d.policy.figure.RectangleSelectionFeedbackPolicy())
        this.assignedFigures.each((i, child)=>{
          child.setVisible(true)
          child.installEditPolicy(this.policy)
          child.getOutputPorts().each( (i, port)=>{
            port.setLocator(port._originalLocator)
            port.setConnectionDirection(port._originalDirection)
          })
          child.portRelayoutRequired = true
          child.layoutPorts()
        })
        this.attr(this.oldDim)
      }
      else{
        this.installEditPolicy(new draw2d.policy.figure.AntSelectionFeedbackPolicy())
        this.oldDim = { width:this.getWidth(), height:this.getHeight()}
        this.assignedFigures.each((i, child)=>{
          // offset of the child and jailhouse shape
          let offset = child.getAbsolutePosition().subtract(this.getAbsolutePosition())
          child.setVisible(false)
          child.uninstallEditPolicy(this.policy)
          child.getOutputPorts().each( (i, port)=>{
            port._originalLocator = port.getLocator()
            // store the applied connection direction (if this used)
            port._originalDirection = port.preferredConnectionDirection
            // and force the current calculated direction
            port.setConnectionDirection(port.getConnectionDirection())
            port.setLocator({
              relocate:  (index, figure) =>{
                figure.setPosition(-offset.x+this.collapsedWidth+1,-offset.y+this.collapsedHeight/2)
              },
            })
          })
          child.portRelayoutRequired = true
          child.layoutPorts()
        })
        this.attr({boundingBox: {x:this.getX(), y:this.getY(),width:this.collapsedWidth, height: this.collapsedHeight}})
      }
    }

    img1.on("click",toggle);
    img2.on("click",toggle);
  },

  assignFigure: function (figure) {
    this._super(figure)

    figure.getPorts().each((i, port) => {
      port.toFront()
      port.getConnections().each((i, connection) => {
        connection.toFront()})
    })

    return this
  },

  /**
   *
   * Return the minWidth of the jailhouse. The minWidth is calculated by care the assigned figures.
   *
   * @returns {Number} the minimum width for the figure
   */
  getMinWidth: function () {
    let width = 0
    this.assignedFigures.each(function (i, figure) {
      if(figure.isVisible()) {
        width = Math.max(width, figure.getBoundingBox().getRight())
      }
    })
    return width - this.getAbsoluteX()
  },

  /**
   *
   * @returns {Number} the minimum height of the figure
   */
  getMinHeight: function () {
    let height = 0
    this.assignedFigures.each(function (i, figure) {
      if(figure.isVisible()) {
        height = Math.max(height, figure.getBoundingBox().getBottom())
      }
    })
    return height - this.getAbsoluteY()
  }
});
```

**Comment by e2sence** [comment]
I have already passed this option ....)))
If you simply hide objects, then when you select the "empty area" under the collapsed parent object, the boundaries of the object will still remain. and yes, folding does not work correctly with connections, look: (start and 'end' shapes coonnected inside jail)
<img width="559" alt="Screenshot 2020-04-19 at 22 39 14" src="https://user-images.githubusercontent.com/32023734/79698017-c462d600-828e-11ea-86f7-049360bb97ac.png">

**Comment by freegroup** [comment]
just unselect the children during the collapse operation (codepen is updated)

**Comment by e2sence** [comment]
Thank you, there is something to think about. but in the presented implementation there are several problems.
![ezgif-6-427a447691c1](https://user-images.githubusercontent.com/32023734/79788802-e2ddd580-8351-11ea-9266-f982e7984704.gif)
this can also be repeated in the example published today

**Comment by freegroup** [comment]
I know. It is the last mile you must go.

Just hide the Connections between figures which has the same Jailhouse parent and the Jailhouse is collapse.

**Comment by e2sence** [comment]
) It's great!
a couple lines of code that handle connections
`port.getConnections().data.forEach(k => {
                                if (k.targetPort.parent.composite.id === this.id && k.sourcePort.parent.composite.id === this.id) {
                                    k.setVisible(false)
                                }
                            })`

**Comment by freegroup** [comment]
good advice - don't use the attributes like "data" or "parent"....this fields can change without any notice. And I do this frequently. Use the getter/setter methods for that. Only the API is stable and no the attributes.

**Comment by e2sence** [comment]
Excellent, thank you. And what about source, target Decorator?
I can't handle them ...

**Comment by freegroup** [comment]
https://github.com/freegroup/draw2d/blob/master/examples/composite_jailhouse/CollapsibleJailhouse.js

**Comment by e2sence** [comment]
> https://github.com/freegroup/draw2d/blob/master/examples/composite_jailhouse/CollapsibleJailhouse.js

but it doesn't work with Decorators

**Comment by e2sence** [comment]
Help me please with Decorators !(
