### ISSUE TITLE
New draw2d examples don't work with touch gestures

### ISSUE THREAD

**Issue by geoffbullen** [freegroup/draw2d#107]
The older draw2d examples use jquery-touch-punch to support mobile device touch gestures.   For example:

OLD: `http://www.draw2d.org/draw2d_touch/jsdoc_6/#!/example/port_hide` - gestures work
NEW: `https://freegroup.github.io/draw2d/index.html#/examples/port_hide` - gestures don't work

However, I couldn't get this to work by adding a touch-punch link to my index.html.    Or, by trying the same example in this github repo.

Would be great to get this working!   I assume I'm missing something obvious

**Comment by freegroup** [comment]
I didn't support touch gesture anymore. I must fix two or three classes to fix....but I'm unable to test it because of the lack of a touch device. (iPad or something in the same size)

**Comment by geoffbullen** [comment]
Oh, that’s a shame.  I just need it to work on small devices to start with.  I’m testing on an iPhone 7.

Thanks

**Comment by geoffbullen** [comment]
@freegroup - if I can help to with this at all, I'd like to.  For example, I have an iPad to test on.
