### ISSUE TITLE
Connection not snapping to custom location on Hub

### ISSUE THREAD

**Issue by mindfuucker** [freegroup/draw2d#108]
![image](https://user-images.githubusercontent.com/5075692/81568325-e5a27800-939d-11ea-8b48-9cd4467bf0c8.png)

The connection from Hub 3 towards Hub 2 only snaps to the corner of the destination hub. I want to override this behavior and snap the targetPort in line with the connection. 

Is this a bug or intended behavior?

**Comment by freegroup** [comment]
is this standard "Hub" from draw2d? I don't think so.

**Comment by mindfuucker** [comment]
@freegroup 

It was an extended hub. Now I have removed all the additional extended features except the hybrid port. It still behaves the same as before.
![image](https://user-images.githubusercontent.com/5075692/81570178-87c35f80-93a0-11ea-8c0e-f012d4e8430d.png)

**Comment by freegroup** [comment]
the Hub uses the the "ShortesPathAnchor" strategie.

```
      this.port.setConnectionAnchor(new draw2d.layout.anchor.ShortesPathConnectionAnchor(this.port))
````

An **anchor** is that point where the connection ends. Normaly this is the related port. But you can plugin any strategy. In the case of a hub this is the shorted path to to the peer node. This works perfect for direct connections but not with ManhattenConnections. Maybe a "VerticalBus" fits better your needs

**Comment by mindfuucker** [comment]
Thank you,

The diagram below is what I want to emulate/recreate with draw2d. The diagram below is made in Microsoft Word.
![image](https://user-images.githubusercontent.com/5075692/81572716-d9b9b480-93a3-11ea-9569-30bacf382f39.png)
As you see I need to be very flexible with positioning the nodes. I have tried the VerticalBus, it has the same problem. 
![image](https://user-images.githubusercontent.com/5075692/81573409-bba08400-93a4-11ea-9043-f58577e6c712.png)
I think I need to overwrite the connectionAnchor and build my own.

**Comment by mindfuucker** [comment]
Putting ports around the figures is my fix. Closing the issue. 
![image](https://user-images.githubusercontent.com/5075692/81577034-45525080-93a9-11ea-9060-f5de0904868d.png)
