### ISSUE TITLE
draw2d.org website: Is the product name Draw2D Touch?

### ISSUE THREAD

**Issue by pflagerd** [freegroup/draw2d#113]
May seem a little silly, but the project's brand matters.

Is the product's proper name "Draw2D Touch" or just "Draw2D"  ?

Or are those two related derivatives of the same base product?

Dan

PS: I have an MBA in addition to a Physics/Math B.Sc. This question is coming from the standpoint of marketing.

**Comment by freegroup** [comment]
Draw2D Touch was the first version of the lib which is based on some bad design decissions. Due the load of the support and I'm unable to scale I continue with a new lib "Draw2D" which isn't backward compatible to the first one.

The new Lib is just on GitHub.
