### ISSUE TITLE
How to force to update the connection?

### ISSUE THREAD

**Issue by Sparks-Lu** [freegroup/draw2d#116]
A connection connects two ports. When one of the ports is moved, the connection is not updated automatically.
Is there any way to force to update the connection?

**Comment by freegroup** [comment]
how do you remove the port? (show your code)

If you delete a figure of type "Node" all related connections are delete automatically.
If you have something like dynamic port you must collect the connections by your own and delete them in the transaction. Normaly with an CommandDelete operation.

**Comment by Sparks-Lu** [comment]
Many thanks for your prompt reply.
The port is moved from one position to the other within the node region. Not removed.
XYRelPortLocator is used for that.
In this case, the related connection is not updated automatically. And I couldn't figure out how to force to update the connection.

**Comment by freegroup** [comment]
normally the Locator is trigged wen the shape is move, resized,...but if you update the Locator itself it seems that the is a missing event.

You can call Locator.relocate(index, port) to update the location of the connections. You can ignore *index* for your kind of locator.

```
locator.relocate(undefined, port)
```

**Comment by Sparks-Lu** [comment]
Tried.
After using locator.relocate(undefined, port), the port is repainted. But unfortunately the connection remains unchanged.
The locator is updated. The port is updated also. But the connections are not updated. As the result, the port and the connection are separated.
Sorry that I started to try this library from yesterday.

**Comment by freegroup** [comment]
today I'm a little bit of pressure....give one day more to create a test scenario...
