### ISSUE TITLE
Chrome update on macos does not redraw background of connections

### ISSUE THREAD

**Issue by icyield** [freegroup/draw2d#120]
Sorry to report that  MacOS "Google Chrome is up to date Version 83.0.4103.97 (Official Build) (64-bit)", has change something that causes connections to not update properly when moved. 

![Screenshot 2020-06-12 at 10 49 42](https://user-images.githubusercontent.com/5418181/84490360-f7c44e80-ac9a-11ea-95fd-b907ff5a04f3.png)

Still works great in safari and firefox on mac.

**Comment by freegroup** [comment]
this is a bug in the "shadow" implementation of the connection. Thanks for the bug report.
I fix this asap.

**Comment by ngfarjad** [comment]
@freegroup  can you please tell me where to look for this? Connection.js ? I can look into it for you. I have temporarily fixed this by not setting outlineColor and stroke.

**Comment by freegroup** [comment]
fixed with draw2d@1.0.38

**Comment by icyield** [comment]
Hi,
    I was already using the latest build not 1.0.37 so the new release at
1.0.38 did not contain anything new. My issue is on MacOS Chrome (after
chrome updated), previously chrome worked fine. I do not know if the issue
is on windows/linux but is still there for MacOs.

Regards

Gerard.
