### ISSUE TITLE
When node is moved, old connection is not cleaned in the canvas

### ISSUE THREAD

**Issue by Sparks-Lu** [freegroup/draw2d#121]
![image](https://user-images.githubusercontent.com/18032226/85009931-cdd6c480-b191-11ea-8a44-41d2faa6a1cb.png)
It happens in below example.
(http://www.draw2d.org/draw2d_touch/jsdoc_6/#!/example/shape_collapsible)
Is there any solution or workaround?
Thanks in advance.

**Comment by freegroup** [comment]
the problems seems to be that the new chrome handles "svg-filter" a little bit different. I didn'T found a workaround.
The the time being I remove the drop shadow effect with the next release until I found a solution.

**Comment by freegroup** [comment]
fixe with draw2d@1.0.38
