### ISSUE TITLE
bug on vew version of chrome

### ISSUE THREAD

**Issue by jcsofts** [freegroup/draw2d#125]
<img width="1074" alt="WeChat310580bdc02877d429872e67bc56bec8" src="https://user-images.githubusercontent.com/33087222/86747343-4254a300-c06e-11ea-8b3e-bc5da7e04756.png">

there are leval a black line after move the connector? the line will be disappear when change the size(make the draw are refresh). the issue only happend on new chrome (Version 83.0.4103.116 (Official Build) (64-bit))

**Comment by freegroup** [comment]
fixed with draw2d@1.0.38

**Comment by jcsofts** [comment]
thanks
