### ISSUE TITLE
Stroke disappears when straight line

### ISSUE THREAD

**Issue by niek1414** [freegroup/draw2d#14]
Hi
First of all, very cool project!
I found a problem while adding some stroke to a connection:
![line](https://user-images.githubusercontent.com/11294766/50056944-27f16680-0164-11e9-84cb-05567e6b8374.gif)
Then i noticed that the same thing happens in the example aswell.
![example](https://user-images.githubusercontent.com/11294766/50056974-874f7680-0164-11e9-9db9-aff0277652bd.gif)
(from the 'connection anchor fan' example but all with stroke show this behavior)
Didn't found the cause so would apprecate it if someone could look for a fix.
Thanks again for creating this project!

**Comment by freegroup** [comment]
fixed with version  1.0.26
