### ISSUE TITLE
setPosition() ignoring Y cooridinates for a Label

### ISSUE THREAD

**Issue by clomas** [freegroup/draw2d#148]
`setPosition()` is ignoring the optional Y coordinate, even when I set `draw2d.geo.Point(0, 200)` 

The label appears @ x: 0, y:0

`setY() ` behaves the same. 

X coordinate work fine in all of the above methods.

**Comment by freegroup** [comment]
https://codepen.io/freegroup/pen/VwjOgvN

works fine....
