### ISSUE TITLE
Figures are still resizable even resizeable = false

### ISSUE THREAD

**Issue by tiendq** [freegroup/draw2d#16]
Create a not resizable figure

```
let node = new draw2d.shape.basic.Rectangle({
    width: 60,
    height: 60,
    resizeable: false,
  });
```
Figure's UI is changed to indicate it is not resizable but actually we can still resize it (with mouse). Add `selectable: false` will hide selection box then we can temporarily disable resizing :)

**Comment by tompuric** [comment]
You may use a install a custom policy shape for your node as shown in the examples here as a current workaround
http://www.draw2d.org/draw2d_touch/jsdoc_6/#!/example/policy_selection_feedback
