### ISSUE TITLE
mouse cursor position is not at true position 

### ISSUE THREAD

**Issue by amiramri0200** [freegroup/draw2d#161]
Hello,
I have used the draw2d library in angular version 10.0.14. I used **draw2d.SetFigure.extend** to use SVG files and add ports to them. the output is attached. in this project, first I read an excel file and then I add cards that are in the excel file. the problem I confronted is that the mouse cursor is not exact. I mean for example when the mouse is on (x,y) = (100,100) it works as if it is on (x,y) = (80,80). How can I fix the problem?
![Inkedmouse_position_porblem_LI](https://user-images.githubusercontent.com/69210887/109617220-5e500c00-7b4b-11eb-84b1-3dc345854413.jpg)
here is the code that I used to upload excel file
![image](https://user-images.githubusercontent.com/69210887/109617335-83dd1580-7b4b-11eb-9860-5343583422dc.png)
![image](https://user-images.githubusercontent.com/69210887/109617359-8ccde700-7b4b-11eb-947d-00332be970a2.png)

**Comment by freegroup** [comment]
this is related to your problem https://github.com/freegroup/draw2d/issues/44
