### ISSUE TITLE
Multiple problems with the Circuits

### ISSUE THREAD

**Issue by pmorim** [freegroup/draw2d#174]
# Initial Questions

1. Are there any plans to add more functionality to this library's 'circuit implementation'?
2. Is there any plans to improve the documentation? I found that some of the code has seemingly impossible syntax.

# Problems

I am trying to use this library, together with React, to make a Web App where you could create/edit circuits. Unfortunately, I am getting some problems:

## JSON IO

I created a simple circuit and then exported it to JSON by following this [example](https://github.com/freegroup/draw2d/tree/master/examples/io_json_basic/) in the docs.

```javascript
() => {
    let writer = new draw2d.io.json.Writer();
    writer.marshal(canvas.current, (json) => {
        // A simple console log of the JSON
        console.log(json);
    });
},
```

But when I tried to read the previously exported JSON to re-create the circuit, I got **a lot** of error and warning messages. Here is a screenshot of a small amount of them:

![image](https://user-images.githubusercontent.com/77199990/117357607-116f1580-aead-11eb-9fc5-61114d0f8f70.png)

## Nodes

There is a visual glitch that, when a connection of the circuit is deleted, it will not delete the node that is shared with other connections. I also noticed that this bug doesn't happen every time because it depends on the order that the connections are deleted.

![image](https://user-images.githubusercontent.com/77199990/117358515-2a2bfb00-aeae-11eb-8890-3dde92212f14.png)

Besides, the two leftmost nodes in the above screenshot should not even exist.

## Undo

The Undo functionality doesn't work properly. For example, if I delete a figure, the undo will not bring it back. The same happens when I rotate a figure; it will not rotate back to its original orientation.

## Grid

I also found that the grid works weirdly. The figures don't attach properly to it, even when the policy was installed on the canvas.

## Touch

I also, for some strange reason, cannot get it to work with a touchscreen. The clicks do not register.

**Comment by freegroup** [comment]
circuit is now alive as its own product.. https://electra.academy/simulator/
