### ISSUE TITLE
Angular example

### ISSUE THREAD

**Issue by p3root** [freegroup/draw2d#18]
Hey!

I want to use draw2d with an angular application, is there anyway to bind eq. the ports, position of elements, etc?

Maybe you could provide an example?

Thanks,
Patrik

**Comment by mhmmdglc** [comment]
++

**Comment by p3root** [comment]
I've already implemented it @mhmmdglc! if you want so see how - check this out!

https://github.com/automatica-core/automatica/tree/master/src/automatica.core/Automatica.WebNew


Greets

**Comment by mhmmdglc** [comment]
Thank you @p3root  . I am looking now 👍

**Comment by mhmmdglc** [comment]
@p3root  I cant work https://github.com/freegroup/draw2d/tree/master/examples/shape_db example.

**Comment by p3root** [comment]
What do you mean?

**Comment by lakinmohapatra** [comment]
Is there any documentation related to the functions associated with Draw2D

**Comment by gurnard** [comment]
@p3root  I went to your link but I don't see any angular, draw 2d or typescript stuff do you still have this implemetation I am struggling getting draw 2d running under angular 6 and the draw 2d wrapper on npm is marked as deprecated with no docs. Any pointers how I can get draw 2d working in angular 6?

**Comment by gurnard** [comment]
@p3root Thanks for sharing your implementation the Automatica.WebNew src. I have been through it but I don't see any draw2d references or anything related to draw2d. Is there any chance you give me a hint where to find your implementation :-)

**Comment by Simon95H** [comment]
Hello everyone!
Is there a reference where I can see the draw2d library integration in Angular?

I installed jquery and jquery-ui. The scripts are in the angular.json under scripts. The draw2d library is also available under scripts.

Did any of you follow through the integration of draw2d in Angular?

I ask for any tips.

Thanks!
