### ISSUE TITLE
draw2d.shape.basic.Text can only be made wider and not narrower when the text contains a '$'

### ISSUE THREAD

**Issue by Wulthan** [freegroup/draw2d#2]
When a Text-shape contains a '$' in the text at any position I am only able to make this object wider. It is not possible to make it narrower on any of the two sides. Tested in Chrome and Firefox.

**Comment by freegroup** [comment]
the example code "galerie_shape_basic" which contains the named text object is working well.
Did you use THIS draw2d version (npm install draw2d) or the legacy one?
which version is reported by npm?

![draw2d_special_char_in_text](https://user-images.githubusercontent.com/1155039/44020795-5bee73f8-9ee3-11e8-8ba1-4e675609cbf2.gif)

**Comment by Wulthan** [comment]
I am using legacy version 6.1.66 and not npm

**Comment by freegroup** [comment]
sorry - no support for the old version on this repo. Just npm
