### ISSUE TITLE
JQuery dependency not defined in package.json

### ISSUE THREAD

**Issue by kagant15** [freegroup/draw2d#20]
I noticed that draw2d uses jQuery throughout its code yet doesn't declare it as a dependency in the package.json.  All the examples load jQuery though the use of a script tag in the head of the document.  What is the reason for not packaging jQuery with draw2d?

**Comment by kleins05** [comment]
FYI: I came across this, too, and opened a pull request to add the dependency https://github.com/freegroup/draw2d/pull/24. Works in my project, but seems to cause issues for freegroup that I don't fully understand yet.
