### ISSUE TITLE
License puzzle

### ISSUE THREAD

**Issue by penghzhang** [freegroup/draw2d#21]
Hi
      We are trying to find a javascript digram framework for our application. And we find Draw2D touch, it is so great. But we are not clear about the license of Draw2D. In our survey, we find there are two licenses of Draw2D. One is GPL2 license(http://www.draw2d.org/draw2d/community.html), the other is MIT license in GitHub(https://github.com/freegroup/draw2d). And our questions are:
       1) why are there two license versions? 
       2) what's the difference of draw2d under these two licenses? such as: source code, features, document and service.
       3) Are both licenses available in reality?
Hope for your reply, thank you very much!

**Comment by freegroup** [comment]
the old "http://www.Draw2D.org" license model didn'T exist anymore. I move all the code to the public repo here.
