### ISSUE TITLE
How to Use ManhattanConnectionRouter with explicit waypoints

### ISSUE THREAD

**Issue by RomanoViolet** [freegroup/draw2d#214]
I am attempting to create a connection between two ports using the [ManhattanConnectionRouter](https://www.draw2d.org/draw2d_touch/jsdoc_6/#!/api/draw2d.layout.connection.ManhattanConnectionRouter). Additionally, I want the specify the waypoints the routing should pass through as an array of x,y points.

I have tried to explicitly populate vertices like so:

```ts
let _con = new draw2d.Connection();
_con.setRouter(new draw2d.layout.connection.ManhattanConnectionRouter());
_con.vertices.clear();
_con.vertices.push(/* an array of {x,y} */);
```

But the line still does not follow the waypoints I specify. I have also tried to use the route( connection, oldVertices, [routingHints] ) method for explicitly specifying waypoints:

```ts
_con.route([{x,y}, ...]);
```

but still the routing does not honor the waypoints.

What am I doing wrong?

**Comment by freegroup** [comment]
it is not possible to add a kind of "waypoints" to this router.
