### ISSUE TITLE
How to develop a custom "input" shape?

### ISSUE THREAD

**Issue by eastxing** [freegroup/draw2d#228]
Hi there,
I have used the old version draw2d.js for years(since 2010).
Now I want to upgrade to the latest new version.
Then I found now all your figure must connect to a shape. My figure contains normal html form field, such as input text, textarea, combo, check box, radio box, ...
My question is what kind of shape should I created for my figure? Can you give some suggestions? Thanks.

**Comment by freegroup** [comment]
sorry - the 2010 version is completely based on HTML. Each "pixel" of the graph is implemented with Div's. No Canvas no SVG at this time. 

In this case, these two libs are not compatible at all. Sorry for this

**Comment by freegroup** [comment]
very very old demo of one of the first versions.  http://freegroup.github.io/draw2d_dhtml/demo/
