### ISSUE TITLE
Images in rectangles not showing in chrome

### ISSUE THREAD

**Issue by gurnard123** [freegroup/draw2d#23]
I have a horizontal layout defined with a basic.Image with a bonding box of a rectangle.
The image is a png image.
In Firefox and Opera the image shows correctly but in Chrome (73.0.3683.86 (Official Build) (64-bit)) it does not.

Inspecting the element in chrome shows me that the image path is correct. This is proven by viewing the image tag in the Chrome console and the image there is visible. Also it shows in FireFox and Opera.

This is my code specifying the image:

```
        this.activityIcon = new draw2d.shape.basic.Image({
            path: '../static/img/tba/activity-script.png',
            width:32,
            height:32,
            minWidth:32,
            minHeight:32,
            boundingBox:new draw2d.geo.Rectangle( 0, 0, 32, 32 ),
            className:'activity-image'
        });

        this.activityBlock = new draw2d.shape.basic.Rectangle({
            bgColor:"#ffffff",
            color:'#'+this.COLOR,
            width:40,
            height:40,
            minWidth:40,
            minHeight:40,
            stroke:1,
            dasharray: ["."]
        });
        this.activityBlock.add(this.activityIcon, new draw2d.layout.locator.CenterLocator());


```

This is a link to a screen shot detailing the issue in chrome

[https://drive.google.com/open?id=1APTY525Ai-NdqxrDlwvpUL5jkNyI1LMM](https://drive.google.com/open?id=1APTY525Ai-NdqxrDlwvpUL5jkNyI1LMM)

**Comment by gurnard123** [comment]
Further more the same images are displayed when used in normal <img tags on the same page.  I was thinking it was png opacity or something but they work on normal <img tags so it is not that. Also tried the images without transparency and still they do not show. So it appears to the the draw2d lib that is failing on Chrome.

**Comment by gurnard123** [comment]
Any ideas on this one. For me this is breaking issue. Images cannot be viewed on chrome.
Any idea of a workaround or any clue where I should start looking?  
Any help or ideas really appreciated.

**Comment by niek1414** [comment]
I would start by playing around with the example to check if that does work.(https://freegroup.github.io/draw2d/io_json_image/index.html)
If it does work (works on my version of chrome) then you can compare it with your code.

**Comment by gurnard123** [comment]
Thanks for the response.
The demo does not work in my Chrome. The images do not show. In Firefox they do.
So there does seem to be a problem with the lib. What version of Chrome are you using I am on 73.
See the screen shot linked:

[https://drive.google.com/open?id=1La_w6rpavtSSJFoyeh_9NHWjjnIxhMap](https://drive.google.com/open?id=1La_w6rpavtSSJFoyeh_9NHWjjnIxhMap)

**Comment by niek1414** [comment]
Interesting, i am at 75 (canary) so it is possible what it was a chrome issue what was fixed.
This library uses svg to show all its elements and if the library creates the correct svg output it should be displayed. Can you see this example by mozilla? https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image#Result
If you can, can you strip the image tag that you can't see until it looks the same?

**Comment by gurnard123** [comment]
Again thanks for the response.  
I cannot see the image on that test page. If I open the js fiddle page and click run on js fiddle the image flashes (really quick if you blink you miss it) into view then is no longer visible. 
I can see the image in my firefox and opera.  

So it seems the browser cannot render a png in place of an SVG is that correct?

**Comment by niek1414** [comment]
Is seems so, what you can do now is check if there is a bug report for it (didn't find it in my quick search) [here](https://bugs.chromium.org/p/chromium/issues/list?can=2&q=SVG+image&colspec=ID+Stars+Pri+Area+Feature+Type+Status+Summary+Modified+Owner+Mstone+OS&cells=tiles) or create one. I never tried this but for your png file you could try and make a svg. That will likely work. You can try to make an svg yourself or try [this service](https://image.online-convert.com/convert-to-svg). Lastly you could try and create a normal `<img>` tag and link it to the `<image>` tag inside the svg with js but that should probably be your last resort as its slow and may introduce unwanted behaviour. 

Good luck!

**Comment by gurnard123** [comment]
I have filed a bug report with Chrome thanks for the link.
Converting to SVG will probably be the simplest route.
Thank you very much for you advice and help
