### ISSUE TITLE
JSONUtil.js in strict mode

### ISSUE THREAD

**Issue by procop95** [freegroup/draw2d#26]
Guys.

here is small issue

due to strict mode in compiled library
/***/ "./src/util/JSONUtil.js":
/*!******************************!*\
  !*** ./src/util/JSONUtil.js ***!
  \******************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";
...

this is not working without declaration (for (key in obj1) {...):
```js
/**
   * @method
   * calculates the diff between the given json objects
   *
   */
  diff: function diff(obj1, obj2) {
    var result = {};
    for (key in obj1) {
      var v1 = obj1[key];
      var v2 = obj2[key];
      if (v1 !== v2) {
        if (v1.equals) {
          if (!v1.equals(v2)) {
            result[key] = obj1[key];
          }
        } else {
          result[key] = obj1[key];
        }
      }
    }
    return result;
  },
```
ReferenceError: key is not defined

thanks
Alex

**Comment by freegroup** [comment]
fixed with 1.0.19
