### ISSUE TITLE
need more detailed documentation.

### ISSUE THREAD

**Issue by steve3d** [freegroup/draw2d#3]
Hi, I'm so glad that this project is still alive. and I want to migrate to this new version, but when I use `npm i draw2d` to install the lib, there is no dist folder, and I can not run any demos.

So I change to `node_modules/draw2d` folder, and install everything with `npm i`, then `npm build` gives a lot of errors.

old documentation at http://www.draw2d.org/draw2d_touch/jsdoc_6/#!/  mentioned nothing about how to use.

so please add some more documentation.

**Comment by freegroup** [comment]
sorry - `dist` folder is dropped by accident by a global **.gitignore** file. I fixed them right now.
A `npm install draw2d --save` should work now

**Comment by steve3d** [comment]
wow, that's quick, but seems you accidentally added `.idea` folder and `.editorconfig` file to the dist repo.

anyway, thank you. and there are some suggestions.

1. since draw2d will to switch to es6, it's time to drop the old `Class.extend` library.
2. hope one day there will be typescript support, at least the type definition.

**Comment by steve3d** [comment]
and another strange thing, why all files created by `npm i draw2d` in `node_modules/draw2d` are created at 1985-10-26 4:15pm? that's 33 years ago?

**Comment by freegroup** [comment]
I didn't know why `npm publish` added the `.idea` folder and why the timestamp is so in the past. Locally everything seems ok...strange.

John Resig `Class` implementation isn't my biggest fault. I think this is the `draw2d.util.ArrayList`
