### ISSUE TITLE
jQuery missing when installing with npm and using with Angular

### ISSUE THREAD

**Issue by florianluediger** [freegroup/draw2d#30]
Hi,

when I try to use draw2d inside my Angular application after installing it via npm, it complains that jQuery is missing.

Steps to reproduce:

1. `npm install jquery`
2. `npm install draw2d`
3. create component with the following code:

```javascript
import {Component, OnInit} from '@angular/core';
import draw2d from 'draw2d';

@Component({
    selector: 'app-canvas',
    templateUrl: './canvas.component.html',
    styleUrls: ['./canvas.component.css']
})
export class CanvasComponent implements OnInit {

    ngOnInit() {
        const canvas = new draw2d.Canvas('canvas');
        const test = new draw2d.shape.basic.Circle({x: 40, y: 10, stroke: 3, color: '#3d3d3d', bgColor: '#3dff3d'});
        canvas.add(test);
    }
}

```

Compilation succeeds without a problem, however when accessing the page with chrome, I get the following error:

```
draw2d.js:28593 Uncaught ReferenceError: jQuery is not defined
    at Object../src/lib/jquery.contextmenu.js (draw2d.js:28593)
    at __webpack_require__ (draw2d.js:30)
    at Object../src/policy/line/OrthogonalSelectionFeedbackPolicy.js (draw2d.js:37081)
    at __webpack_require__ (draw2d.js:30)
    at Object../src/index.js (draw2d.js:20140)
    at __webpack_require__ (draw2d.js:30)
    at draw2d.js:94
    at draw2d.js:97
    at webpackUniversalModuleDefinition (draw2d.js:3)
    at Object../node_modules/draw2d/dist/draw2d.js (draw2d.js:10)
```

**Comment by freegroup** [comment]
you must add this manually in your application.

**Comment by GeorgievGG** [comment]
> Hi,
> 
> when I try to use draw2d inside my Angular application after installing it via npm, it complains that jQuery is missing.
> 
> Steps to reproduce:
> 
> 1. `npm install jquery`
> 2. `npm install draw2d`
> 3. create component with the following code:
> 
> ```js
> import {Component, OnInit} from '@angular/core';
> import draw2d from 'draw2d';
> 
> @Component({
>     selector: 'app-canvas',
>     templateUrl: './canvas.component.html',
>     styleUrls: ['./canvas.component.css']
> })
> export class CanvasComponent implements OnInit {
> 
>     ngOnInit() {
>         const canvas = new draw2d.Canvas('canvas');
>         const test = new draw2d.shape.basic.Circle({x: 40, y: 10, stroke: 3, color: '#3d3d3d', bgColor: '#3dff3d'});
>         canvas.add(test);
>     }
> }
> ```
> 
> Compilation succeeds without a problem, however when accessing the page with chrome, I get the following error:
> 
> ```
> draw2d.js:28593 Uncaught ReferenceError: jQuery is not defined
>     at Object../src/lib/jquery.contextmenu.js (draw2d.js:28593)
>     at __webpack_require__ (draw2d.js:30)
>     at Object../src/policy/line/OrthogonalSelectionFeedbackPolicy.js (draw2d.js:37081)
>     at __webpack_require__ (draw2d.js:30)
>     at Object../src/index.js (draw2d.js:20140)
>     at __webpack_require__ (draw2d.js:30)
>     at draw2d.js:94
>     at draw2d.js:97
>     at webpackUniversalModuleDefinition (draw2d.js:3)
>     at Object../node_modules/draw2d/dist/draw2d.js (draw2d.js:10)
> ```

Apparently, you need to add this code:
 "scripts": [
              _"node_modules/jquery/dist/jquery.js",
              "node_modules/jquery-ui-dist/jquery-ui.min.js"_
            ]

In your angular.json file.
