### ISSUE TITLE
ArrayList's each() function iterates via index over a mutable list

### ISSUE THREAD

**Issue by Thusnake** [freegroup/draw2d#39]
Say you would like to deselect some items and you call `canvas.getSelection().each()`, supplying it with a function that will remove the passed item from the selection if it meets some criteria. The result would likely be that some of the items which should have been removed from the selection stay selected.

The reason behind this is the way `each()` iterates over the elements. It uses a standard `for` loop, which means that an array index is used, which is incremented at each step. But when the item at the current index (say `data[2]`) is removed from the list, the next item (`data[3]`) will replace it (becoming `data[2]`), as the list is automatically shifted left to fill the gap. On the next cycle the index will increase and the item accessed will be `data[3]`, which is what used to be `data[4]` and we've missed the original `data[3]`, which can now be found at `data[2]`.

This issue is remedied within the source code by using `canvas.getSelection().getAll().each()`, which creates a copy of the list and iterates over it. That way even if the order of the list is modified, because the copy stays the same all of the items will be accessed.

There is an exception though - Canvas' function `setCurrentSelection()` uses an `each()` without calling `getAll()` first to deselect all of the currently selected elements. This results in only half of the items being deselected, the rest remaining selected. Because of this, `setCurrentSelection()` is pretty much unusable and there is no alternative (other than copying the source code) for setting the selection manually.

An obvious solution would be to have `each` iterate over the result of `getAll` instead of the original array. Using the built-in `data.slice()` with no arguments would create a copy just as well.

**Comment by freegroup** [comment]
if you want to edit the list or remove elements you should use ArrayList.grep method to remove elements from the list.
