### ISSUE TITLE
Scrolling breaks coordinates despite ScrollArea set

### ISSUE THREAD

**Issue by Demak** [freegroup/draw2d#44]
Hello, I am using draw2d to create an editor inside existing interface. I am creating canvas inside a block with fixed width and height and later canvas can increase in size if more space is needed for diagram. The problem is that when canvas is larger than its container and container is scrolled, selection on canvas is not aligned to cursor anymore. Difference seems to be exactly same as scrolled distance. scrollArea of canvas is set to the container element on which scroll appears. If I am not setting scrollArea then there is no offset on canvas coordinates, but ```canvas.getScrollTop()``` is always returning 0, which breaks other things.
I have attached an archive with simple example demonstrating this problem, could you please take a look and tell me what am I doing wrong.
[scroll.zip](https://github.com/freegroup/draw2d/files/3477570/scroll.zip)
![Menu_059](https://user-images.githubusercontent.com/5584155/62632969-0a178280-b93c-11e9-9f01-200f5c59495a.png)

**Comment by freegroup** [comment]
wrong scroll area, the line below is working.

```javascript
    canvas.setScrollArea('#draw');
```

if you have a more complicated setup, you can implement the two functions below to your needs. (Extend the Camvas class ) 

```javascript

var MyCanvas = draw2d.Canvas.extend({

  init: function (id) {
    this._super(id)
  }
  .
  .
  .
  .

  /**
   * @method
   * Transforms a document coordinate to canvas coordinate.
   *
   * @param {Number} x the x coordinate relative to the window
   * @param {Number} y the y coordinate relative to the window
   *
   * @returns {draw2d.geo.Point} The coordinate in relation to the canvas [0,0] position
   */
  fromDocumentToCanvasCoordinate: function (x, y) {
    return new draw2d.geo.Point(
      (x - this.getAbsoluteX()) * this.zoomFactor,
      (y - this.getAbsoluteY()) * this.zoomFactor)
  },

  /**
   * @method
   * Transforms a canvas coordinate to document coordinate.
   *
   * @param {Number} x the x coordinate in the canvas
   * @param {Number} y the y coordinate in the canvas
   *
   * @returns {draw2d.geo.Point} the coordinate in relation to the document [0,0] position
   */
  fromCanvasToDocumentCoordinate: function (x, y) {
    return new draw2d.geo.Point(
      ((x * (1 / this.zoomFactor)) + this.getAbsoluteX()),
      ((y * (1 / this.zoomFactor)) + this.getAbsoluteY()))
  }
})

```

**Comment by Demak** [comment]
Thanks for your help, although setting canvas scroll area to its html element ("#draw" in this case) didn't worked (well, it did fixed selection but canvas.getScrollTop() was always zero), extending canvas and changing coordinates calculation did the job.

**Comment by ArkangelGammar** [comment]
Hi, 
I'm facing a similar problem. I have and issue when tha pages is zoomed. With 67 % zoom it work everything excelent. But with a 100 % zoom i face the same calculation problem and i cant figure it out. I tried setting canvas scroll area and changing coordinates calculations but nothing works. I'm still have an offset between object and mouse cursor.

Regards

**Comment by ArkangelGammar** [comment]
> Hi,
> I'm facing a similar problem. I have and issue when tha pages is zoomed. With 67 % zoom it work everything excelent. But with a 100 % zoom i face the same calculation problem and i cant figure it out. I tried setting canvas scroll area and changing coordinates calculations but nothing works. I'm still have an offset between object and mouse cursor.
> 
> Regards

An important thing I forgot to say. I'm using jquery 3-3-1, and i have to use the noconflict method

**Comment by Shashank-Bhatt1** [comment]
Hi FreeGrouop, 
Thanks for this awesome library.
After setting correct scrollArea, selection issue seems to be fixed.
However, there appears to be a wrong dropping on canvas (exactly same as in case of selection of Figure). 
When we drop, it drops at additional scrolled area from top due to addition of extra scrollTop in above `fromDocumentToCanvasCoordinate` method. Any solution for that?
