### ISSUE TITLE
Can't resize Canvas and Zoom Figures

### ISSUE THREAD

**Issue by InannaInai** [freegroup/draw2d#46]
Dear Freegroup,

I'm trying to develop a application where I'm able to drop buttons from out of a canvas in a canvas and move them around and zoom in the canvas.
For convinience I don't want the size if that canvas to be to large in the beginning.

As I'm new in jquery and naturally also in draw2d for better understanding I'm trying to solve my porblems with the help of your [example](http://www.draw2d.org/draw2d_touch/jsdoc_6/#!/example/buildin_commandstack).

For the canvas I've placed following code:
 ```
  <div id="content">
   		<div id="canvas" class="" ></div>
   </div>
```
My CSS has canvas set on:
```
#canvas {
	padding: 0px;
	margin: 0px;
	margin-left: 5%;
	width: 70%;
	height:20vw;
	border: 1px solid gray;
	overflow:auto;
	resize: both;
}
```

As for the application.js, I did not want to use the 'jquery-ui-1.8.16.custom.css' that you have used, as I dont want to split my window.  So I've reduced the application,js to this:
```
var app = {};

app.Application = Class.extend({
	NAME : "app.Application",

	init : function() {
		this.view = new app.View("canvas");
	}
});
```
As for the View.js its the same as in the example. 

Now I'd like to state my problems:
1. I can't resize my canvas as long as the code "this.view = new app.View("canvas");" is activated. But if I deactivate this code then I can't drag and drop the buttons anymore.
![grafik](https://user-images.githubusercontent.com/53942989/62847409-81e80300-bcd6-11e9-8c77-36b0c90ae1d5.png)
As you can see, I have this corner and also the arrows, but when I try to resize the canvas I'm starting a selection inside the canvas .

2. If I try to zoom with 'shift'+'Mouse' than it zooms the content out of the canvas.
In the picture below you can see that the canvas's size should end where the border is, but when I zoom, they zoom out, like in that picure:

Before zoom:
![grafik](https://user-images.githubusercontent.com/53942989/62847839-c4aada80-bcd8-11e9-85bb-1d60a3785116.png)

After zoom:
![grafik](https://user-images.githubusercontent.com/53942989/62847847-d5f3e700-bcd8-11e9-89e6-bbd43bf435e5.png)

Hopefully you can help me here as well!

Best regards

**Comment by InannaInai** [comment]
Ok, I've kinda solved the problem with the zoom. I've changed the svg to relative instad of absolute in my css class.
That works, but it's still not possible to resize the canvas-div

**Comment by freegroup** [comment]
did the method `Canvas.setDimension` didn't work for you?

**Comment by InannaInai** [comment]
No, it did not work.

At least not if I'm using Application.js and View.js as in the examples.

**Comment by InannaInai** [comment]
It's stll not possible to resize the canvas-svg. I've created a workaround where I've initialized the SVG as a very large element. Then I've wapped this element in a div-container and reduced the size to my liking.
```
<div id="wrapper">
      <div id="canvas" />
</div>
```

It's not exactly how I've hoped it to be, but its OK now.
