### ISSUE TITLE
connection locator label in json

### ISSUE THREAD

**Issue by majsterkoo** [freegroup/draw2d#50]
Hi,
in this example http://www.draw2d.org/draw2d_touch/jsdoc_6/draw2d/examples/code_snippets/connection_locator/index.html there is a connection locator with custom label. If I use draw2d.io.json.Writer in this example to create json object, connection_locator is missing.
Is there a possible solution how to add connection locator with label ("I'm a label") with using json out-of-box?

Thanks for reply.

**Comment by freegroup** [comment]
https://freegroup.github.io/draw2d/io_json_dyn_labels/index.html

the important part is to render the dynamic children as well to the JSON.
Normaly you add the label in the init-method of the class. But sometimes it is 
more dynamic. In this case see:

https://freegroup.github.io/draw2d/io_json_dyn_labels/LabeledEnd.js

**Comment by majsterkoo** [comment]
Thank you very much! You solved my problem :)
