### ISSUE TITLE
Is it possible so zoom single rects?

### ISSUE THREAD

**Issue by InannaInai** [freegroup/draw2d#51]
Hi,

I'd like to make a single rect zoomable so that only the rect, but not the whole svg/canvas zooms. 

I dont want to zoom all the rects, only the one I have focus on.

Is that possible? If yes, can you tell me how? (or do you have an exercise?)

Thanks!

**Comment by jdittrich** [comment]
Zoom implies (at least for me) that one zooms into a canvas. Is it "scaling a single rectangle" (maybe with your mousewheel) what you aim for?

**Comment by InannaInai** [comment]
Hi jdittrich,

thats correct and again not completly correct.
I'd like to scale one rect into a number of other rects.

One rect should contain the data of a different rect collection. On scalling (for example after selecting this rect) I'd like this rect to scale into the diffrent collection.
Just so that one can have a better overview if there are a looot of rects with conntections in the canvas.

Is this possible?
I've only found the zooming for the complete canvas so far.

**Comment by freegroup** [comment]
I think you want a kind of "expand a single object" or drill down....but this is not supported
