### ISSUE TITLE
How can I avoid windows 'delete ' keyboard

### ISSUE THREAD

**Issue by the17thDog** [freegroup/draw2d#53]
Windows system, the selected Figure, 
when the I pressed 'delete' key will remove the Figure, but I did not listen to this event.
How can I avoid it?

**Comment by Demak** [comment]
You can set shape as undeletable via `setDeleteable` method after creation.
http://www.draw2d.org/draw2d_touch/jsdoc_6/#!/api/draw2d.Figure-method-setDeleteable

Example:
```javascript
var label = new draw2d.shape.basic.Label({ text: 'This should not be deleted'});
label.setDeleteable(false);
canvas.add(label);

**Comment by the17thDog** [comment]
> You can set shape as undeletable via `setDeleteable` method after creation.
> http://www.draw2d.org/draw2d_touch/jsdoc_6/#!/api/draw2d.Figure-method-setDeleteable
> 
> Example:
> 
> ```js
> var label = new draw2d.shape.basic.Label({ text: 'This should not be deleted'});
> label.setDeleteable(false);
> canvas.add(label);
> ```

thank u guys
