### ISSUE TITLE
Is there any autospacing functionallity?

### ISSUE THREAD

**Issue by wattzor** [freegroup/draw2d#55]
Im using the shape_db example, and i created some Shapes from a json.

They all have x and y set to 0.

Is there some autospace-function to spread out the Shapes over the canvas?

Thanks!

**Comment by Demak** [comment]
As far as I know there is none. There is a built-in way to check if shapes intersect though:
http://www.draw2d.org/draw2d_touch/jsdoc_6/#!/api/draw2d.Figure-method-getBoundingBox
http://www.draw2d.org/draw2d_touch/jsdoc_6/#!/api/draw2d.geo.Rectangle-method-intersects
so to check if two shapes collide use
```javascript
if(shape1.getBoundingBox().intersects(shape2.getBoundingBox()))
```
You can check against all shapes on the canvas by looping through shape list
```javascript
let newFig = new draw2d.shape.basic.Rectangle({x:130,y:30,width:100,height:60});
canvas.getFigures().each((i, figure)=>{
	if(newFig.getBoundingBox().intersects(figure.getBoundingBox())) console.log('collision');
})
```

**Comment by freegroup** [comment]
sorry - draw2d didn't have any autolayout functionality inside
