### ISSUE TITLE
yarn run dev gets stuck on 95%

### ISSUE THREAD

**Issue by internationalhouseofdonald** [freegroup/draw2d#59]
Hello, and thank you for this wonderful library! Following the instructions in README.md;
I clone the repository and run `npm install` and `yarn dev` only to find that `yarn` gets stuck on 95%. 

Have you ever seen this type of behavior before?

![image](https://user-images.githubusercontent.com/20768148/65955311-7929c880-e40d-11e9-8b60-06264731a57d.png)

Do you need any more screenshots or logs?

I'm using `yarn` [v1.19 (stable)](https://yarnpkg.com/lang/en/docs/install/#windows-stable) on Powershell 2 in Windows 10.

**Comment by igihcksn** [comment]
@internationalhouseofdonald have you solve this issue? i have the same problem before, when installing package with npm stuck on draw2d package, i have tried to remove package draw2d from package.json and im installing manual with "npm install draw2d"

**Comment by internationalhouseofdonald** [comment]
@igihcksn I have not. I ended up going with SVG.js

**Comment by freegroup** [comment]
should be fixed.
