### ISSUE TITLE
versioning  6.1 to 1.0

### ISSUE THREAD

**Issue by gurnard123** [freegroup/draw2d#6]
Hello. 

I have been using draw2d for some years now. The recent version I am using was bought from the website draw2d.org. I have version 6.1.52.  Now I have been directed to this git repository but the version in the package.json reads 1.0.14.  

So have version numbers started over or is this a really old version here on git hub?
If this is a new version are there any breaking changes from 6.1.52 to 1.0.14.

I notice that the dist files are different. Before there were many separate files and now just the one. Can I switch out the libs for the single file?  Or will my code just explode after this.

thanks

**Comment by freegroup** [comment]
there are some breaking changes in version 1.#. this repo is the new version of draw2d and
the old code is out of maintenance. 

new code drops some deprecated methods and switches more and more to es6

**Comment by gurnard123** [comment]
Can you share what the breaking changes are, or is it a secret that I have to discover for myself :-)

**Comment by freegroup** [comment]
because draw2d is a complete new *project* I didn't care about compatibility and in this case I didn't have any list of breaking changes. It is up to you to check if your app is working with this *new* lib.

**Comment by gurnard123** [comment]
OK so you recommend I stay on the old 6.x version then?
So this is a completely new project?  But the examples are the same from the old one, even the same js files within the examples.  So is there any unit testing on this library?
