### ISSUE TITLE
Can't access rect correctly after scrolling Window

### ISSUE THREAD

**Issue by InannaInai** [freegroup/draw2d#64]
Dear freegroup,

I don't know if this is a svg-problem or a draw2d-Problem therefore I'm opening this issue.

I have a problem with scrolling:
I've created a canvas in a div and placed tis div in an other div so that I can resize this div:

```
<div id="initialCanvas">
		<div id="gfx_holder" onselectstart="javascript:/*IE8 hack*/return false"  class=""></div>
	</div>
```

Than I've added some css so that I could scroll in the initialCanvas.
```
#initialCanvas {
	border: 1px solid gray;
	margin: 0px;
	margin-left: 1%;
	width: auto;
	height: 20vw; 
	overflow: auto !important;
	resize: vertical !important;
	background-color: #e6e6e6;
}

#gfx_holder {
	margin: -27px;
	padding: 0 !important;
	border: 1px solid #f2f2f2;
	background-color: #e6e6e6;
	width:6000px; 
	height:6000px;
}

svg {
	position: relative !important;
	border: 1px solid #e6e6e6;
	background-color: white;
        width:"100%";
        height: "100%";
}
```
And this works as expected. But now I've found a new problem.
If I resize my browser-window (I don't mean the initial div), than I can't click on my rects directly. I have to click beneath the rect. How much beneath depends on the amount of scrolling I have done.

For visual:
If I don't scroll the window, like in this, than I can click in the rect:
![grafik](https://user-images.githubusercontent.com/53942989/67680389-6f9f6c00-f98b-11e9-9624-720f37c61a7c.png)
But If I scroll the window and try to click on the rect I'm geting this:
![grafik](https://user-images.githubusercontent.com/53942989/67680512-a8d7dc00-f98b-11e9-9c71-6b086a847ea9.png)
I can only move/select the rect if i click below the rect (how much below depends on the amount of scrolling tha I've done.)
![grafik](https://user-images.githubusercontent.com/53942989/67680602-d58bf380-f98b-11e9-8483-5ce49ba72769.png)

When creating the canvas I'm setting the scrollarea to `canvas.setScrollArea("#gfx_holder");`

How can I solve this problem?

Best regards

**Comment by InannaInai** [comment]
I found the Solution:
var canvas = new draw2d.Canvas("gfx_holder");
canvas.fromDocumentToCanvasCoordinate = $.proxy(function(x, y) {
    return new draw2d.geo.Point(
            (x + window.pageXOffset - this.getAbsoluteX() + this.getScrollLeft())*this.zoomFactor,
            (y + window.pageYOffset - this.getAbsoluteY() + this.getScrollTop())*this.zoomFactor);
},canvas);

canvas.fromCanvasToDocumentCoordinate = $.proxy(function(x,y) {
    return new draw2d.geo.Point(
            ((x*(1/this.zoomFactor)) + this.getAbsoluteX() - this.getScrollLeft() - window.pageXOffset),
            ((y*(1/this.zoomFactor)) + this.getAbsoluteY() - this.getScrollTop() - window.pageYOffset));
},canvas);

**Comment by MosabAbuzaid** [comment]
Hi @InannaInai 

that's worked when I tried to drag and drop new table but what if want to make the canvas scroll down and left when moving a table or connect between 2 tables one of them is out the visible area did you find a solution for that?

**Comment by InannaInai** [comment]
Well, there is a problem when I'm holding a table and scrolling. There is no problem with connecting a table from a visible area to an invisible. I can't scroll left or right with my mouse, therefor I can't go left or right with the table.
Usualy I'd trop the table far right, than scroll it, so that the table is on the left edge and than I'd pick the table up again and move it again. I know it's not the best solution but I'm still new with this whole javascript/jquery thing.

**Comment by MosabAbuzaid** [comment]
I hope that if I can find a solution to make the scrolling while dragging smooth like dragging a new table 😢

**Comment by MosabAbuzaid** [comment]
Hi @InannaInai 
did you found some great ideas or not yet? 😅
