### ISSUE TITLE
Math.sign polyfill issue

### ISSUE THREAD

**Issue by rikschennink** [freegroup/draw2d#67]
Hi,

In `src/util/Polyfill.js` you're polyfilling `Math.sign` without checking if it's offered by the browser. This snippet:

```js
Math.sign = function () {
    if (this < 0) {
        return -1;
    }
    return 1;
};
```

The polyfill however doesn't behave the same as the default `Math.sign`. So including Draw2D might cause other frameworks/libraries to stop working (which I'm seeing with my product [Doka](https://pqina.nl/doka/)).

I replaced the polyfill with [the one offered on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sign#Polyfill) (I removed the feature test just to make sure this was the issue, but you should leave it in).

```js
Math.sign = function(x) {
    // If x is NaN, the result is NaN.
    // If x is -0, the result is -0.
    // If x is +0, the result is +0.
    // If x is negative and not -0, the result is -1.
    // If x is positive and not +0, the result is +1.
    return ((x > 0) - (x < 0)) || +x;
    // A more aesthetic pseudo-representation:
    //
    // ( (x > 0) ? 1 : 0 )  // if x is positive, then positive one
    //          +           // else (because you can't be both - and +)
    // ( (x < 0) ? -1 : 0 ) // if x is negative, then negative one
    //         ||           // if x is 0, -0, or NaN, or not a number,
    //         +x           // then the result will be x, (or) if x is
    //                      // not a number, then x converts to number
  };
```

This solved the issue I'm seeing with [Doka](https://pqina.nl/doka/) but I don't know how that affects Draw2D as it seems it's written based on the incorrect polyfill version.

**Comment by freegroup** [comment]
Thanks for the bug report. I removed the obsolete polyfill at all.
