### ISSUE TITLE
CommandRotate Issue

### ISSUE THREAD

**Issue by ganbayar13** [freegroup/draw2d#68]
There is an error on execute draw2d.command.CommandRotate(figure, angle) after I relocate connections manually. I am using InteractiveManhattanConnectionRouter. 
Error message is "Cannot read property 'getSize' of undefined".

**Comment by ganbayar13** [comment]
![Annotation 2019-12-31 011703](https://user-images.githubusercontent.com/8615067/71592453-43f75880-2b6b-11ea-9cf8-247cbd6e6313.png)
Getting error on this line.

**Comment by freegroup** [comment]
should be fixed in the latest version on Github.
I saw this error as well .
