### ISSUE TITLE
Moving shapes around canvas

### ISSUE THREAD

**Issue by procop95** [freegroup/draw2d#7]
Dear Andreas, guys.
First of all, really appreciate you decision to give MIT license to this project!!!

here is issue: 
if i create canvas this way:
    canvas = new draw2d.Canvas("canvas", 2000,2000);
    canvas.setScrollArea("#canvas");

it became impossible to move shapes outside initial viewport, however canvas is 2000x2000 by rights.
you can see this behaviour in "composite group" example. 

thanks
Alex

**Comment by freegroup** [comment]
if you create a canvas of 2000x2000 it is not possible to move the shapes outside. Yes.
Because the canvas is only 2000x2000

**Comment by procop95** [comment]
I'm afraid you got me wrong. I mean, you cannot move shape outside initial canvas visible part which is smaller then requested 2000X2000. So you can scroll till 2000 but cannot move shapes there.
Please check  "composite group" example.
![draw2d](https://user-images.githubusercontent.com/8001668/46735591-d8ed0800-ccc0-11e8-84e2-54fca593b0f5.gif)

**Comment by freegroup** [comment]
thanks. I got it. 

I fixed the demo. The main problem was, that the size of the scrolling canvas was overridden by CSS.
This logic breaks all. I fixed the demo with 1bef65576a96df5060db8c4effdb0d14e3a2832c

**Comment by procop95** [comment]
thanks Andreas. I'll try fix my project too .
 I c you change call to:
canvas = new draw2d.Canvas("canvas");
will 'draw2d.Canvas(element, width, height)' support remain? 
BTW there is no scrolling in example now, if you didn't mean that.
thanks once more

**Comment by sashabaranov** [comment]
Here you also cannot move stuff beyond initial area
