### ISSUE TITLE
Typos on the draw2d.js installed through npm

### ISSUE THREAD

**Issue by bettimms** [freegroup/draw2d#70]
I'm facing issues to load from JSON and when implementing `Shift+Drag` to make a copy of the element. I took `script` references from this example (https://codepen.io/desean1625/pen/WqpXqK) and i found it's working. Apparently there seems a difference in the `draw2d` that comes when installing via `npm i` and the scripts references on the example. I did a comparison and i found these issues in the `draw2d` installed using `npm`:

Should be `function` but it's `funktion`:
<img width="1025" alt="Screen Shot 2020-01-10 at 2 27 42 PM" src="https://user-images.githubusercontent.com/9863453/72147062-35087580-33b7-11ea-915e-8f1db2222920.png">

Should be `push` but it's `oush`:
<img width="1048" alt="Screen Shot 2020-01-10 at 2 37 24 PM" src="https://user-images.githubusercontent.com/9863453/72147068-38036600-33b7-11ea-9d75-e24b166fd5d3.png">

I don't know whether these can cause any of the issues I'm facing but with the latest script installed through `npm` are not working.

**Comment by freegroup** [comment]
NPM package isn'T supported anymore.
the named bugs are already fixed in the normal (this) repo.

**Comment by akoskm** [comment]
> NPM package isn'T supported anymore.

@freegroup what does this mean? We can't install the package anymore with npm/yarn?

**Comment by freegroup** [comment]
you can install via NPM or YARN.....but the typical usage with

``` 
const draw2d = require("draw2d");
```

will not work. Loading a JSON draw2d file isn't possible.

**Comment by akoskm** [comment]
Any plans to fix that? It would improve user experience a lot.

**Comment by freegroup** [comment]
no idea how to fix this....
