### ISSUE TITLE
Json-Export does not export everything

### ISSUE THREAD

**Issue by InannaInai** [freegroup/draw2d#72]
Dear freegroup,

I tried exporting my svg like you showed in the examples but it does not export everything.
For example it does not export the labels of my connections.

I'm exporting it like this:
```
canvas.getCommandStack().addEventListener(function(e){
		      if(e.isPostChangeEvent()){
		          displayJSON(canvas);
		      }
		  });
var jsonData=new Object();
		var writer = new draw2d.io.json.Writer();
		writer.marshal(canvas,function(json){
		       $("#json").text(JSON.stringify(json, null, 2));
				alert(jsonData);
				var url = "SVGServlet";
				$.ajax({
					type : "POST",
					url : url,
					data: {jsonData:JSON.stringify(json, null, 2)},
					success : function(data) {
						//successfully saved
					}
		              }
				});   
		    });
```
```
 function displayJSON(canvas){
	    var writer = new draw2d.io.json.Writer();
	    writer.marshal(canvas,function(json){
	        $("#json").text(JSON.stringify(json, null, 2));
	    });
```

The end result shows something like this:

```
{
    "type": "draw2d.Connection",
    "id": "24b5e7b5-bfbd-d960-f8a5-5fa73b38506f",
    "alpha": 1,
    "angle": 0,
    "userData": {},
    "cssClass": "draw2d_Connection",
    "stroke": 2,
    "color": "#00A8F0",
    "outlineStroke": 0,
    "outlineColor": "#30FF30",
    "policy": "draw2d.policy.line.OrthogonalSelectionFeedbackPolicy",
    "vertex": [
      {
           {
        "x": 216.3000030517578,
        "y": 143.63333129882812
      },
      {
        "x": 301.8000030517578,
        "y": 143.63333129882812
      },...
      }
}
```
But it does not export any labels. Do you have any idea where the problem lies?

Best regards,

**Comment by InannaInai** [comment]
I've created a workaround whitch works in my case. But I won't call it the best way. Would be nice if the lib could do this on its own.

I've added the following code to draw2d.js to ` getPersistentAttributes: function getPersistentAttributes() {`

```
    if (typeof this.label  !==  'undefined') {
        if (this.label !== null) {
            memento.label = this.label.text;
        }
    }
```

**Comment by bettimms** [comment]
@InannaInai at which line #. I've made a workaround for export as well but now import has issues.

**Comment by InannaInai** [comment]
![grafik](https://user-images.githubusercontent.com/53942989/72338149-288c6180-36c4-11ea-91ac-84ee89afd94c.png)

But I'm not sure if it will work on import. I have not tried that yet.
Linenumber 12100
Hope it works for you, than it will work for me as well ^^

**Comment by InannaInai** [comment]
Ok, now in line 12117+  add to:

 ```
 /**
   * @method
   * Read all attributes from the serialized properties and transfer them into the shape.
   *
   * @param {Object} memento
   */
  setPersistentAttributes: function setPersistentAttributes(memento) {
    this.id = memento.id;
[...]
```
this:
```
  if (typeof memento.label !== "undefined") {
       if (typeof this.label === "undefined") {
           this.label = new draw2d.shape.basic.Label({
               text:memento.label,
               color:"#0d0d0d",
               fontColor:"#0d0d0d",
               bgColor:"#ffffff"
           });
          this.add(this.label, new draw2d.layout.locator.ManhattanMidpointLocator());
       
       }else{ this.label.text=memento.label;}
      }
```
It's possible to export.
Info: I'm only using labels on SOME connections and not on figures like rects. Therefore I have not tested this solution with rects. But at least I have my labels exported and imported.

**Comment by bettimms** [comment]
Apparently for my cases it's not working. I've made custom shapes combined with labels. Thanks for sharing anyway.

**Comment by bettimms** [comment]
This is my custom serializer for export. Note that for custom figures i set the type to `userData` prop to keep track the origin of the figure. Import didn't work yet.

```javascript
draw2d.io.json.Writer.prototype.canvasToJson = function(
  canvas,
  resultCallback
) {
  let result = [];

  //TODO: Fix the bug with the latest version using npm
  //When serializing twice, labels(LabeledEnd) are added twice in the second time
  canvas.getFigures().each(function(i, figure) {
    const currentFigureProps = figure.getPersistentAttributes();
    if (!currentFigureProps.labels) currentFigureProps.labels = [];

    figure.children.data.forEach(e => {
      let childFigure = e.figure;
      const userData = childFigure.userData;
      let childWithProps = childFigure.getPersistentAttributes();

      if (userData) {
        currentFigureProps.type = userData.type;
        childWithProps.locator = e.locator.NAME;
      }

      const elementExist = currentFigureProps.labels.find(x=>x.id === childWithProps.id);
      if(!elementExist) currentFigureProps.labels.push(childWithProps);
    });

    result.push(currentFigureProps);
  });

  canvas.getLines().each(function(i, element) {
    result.push(element.getPersistentAttributes());
  });

  resultCallback(result);
};
```

**Comment by InannaInai** [comment]
I think, in theory if you change the figure.js and add label to PersistentAttributes you may be able to add a figure with a label. 
Have not tried that because I don't need it (lucky me).
An other workaround would be to add the data of the label to userData and link this Data to your label.
Like this:
`userData:{myLabel: "some text"}` 

So, when you create your label you'd do something like this:
```
this.label = new draw2d.shape.basic.Label({
                    text:this.getUserData().myLabel,
                    color:"#0d0d0d",
                    fontColor:"#0d0d0d",
                    bgColor:"#f0f0f0"
                });
```
Now, whenever you import your shape with the userData it will create the label with the text you have chosen.

I've done the same thing with my tooltips, therefore I'm quite sure it will work with labels as well. 
You'd just have to ajust your functions you've done so far.

I hope that this can help you.

I know its not the most elegant solution but as long as it does not work otherwise its ok. You wont have to change the lib with this.

**Comment by bettimms** [comment]
Thanks for sharing, unfortunately I'm not keeping track of the text only, I've to keep track of every property and every object in my case as embedded label. So for me the only thing that may work is write down my own serializer and deserializer of the canvas(since the existing one it's buggy).
