### ISSUE TITLE
Bug: when using same port

### ISSUE THREAD

**Issue by InannaInai** [freegroup/draw2d#73]
There is a bug when you establish a connection between one source rect and one or more target rects.

I have a rect which has one output-port but can create a connection with more then one other rect,

When creating the first connection, everything works perfecly. I'm getting something like this:

```
 "source": {
      "node": "cadf9daa-c0d4-c294-5c16-8649f62b6337",
      "port": "output0"
    },
    "target": {
      "node": "969678c7-c0f6-372f-fe0d-413a34a9a9f1",
      **"port": "input0"**

    }
```

But when I connect the same output-port to an other rect, it happens sometimes that I'm getting
  ```
"source": {
      "node": "308288e5-e088-69d8-653a-23d0f5f7d7a9",
      "port": "input0"
    },
    "target": {
      "node": "969678c7-c0f6-372f-fe0d-413a34a9a9f1",
      **"port": "output0"**
    }
```
When I try to connect this output of a figure, which already has a connection, to an other rect it looks like this:
![grafik](https://user-images.githubusercontent.com/53942989/72435734-12070880-379f-11ea-839e-fb2742597b99.png)

Hope you can help me fix the bug.

**Comment by freegroup** [comment]
Unfortunately I do not quite understand the question.

Not: Source and Target of an connection isn't always Output/Input ports. This depend how you create the connection.

If you drag&drop the InputPort to the OutputPort or OutputPort->InputPort. 
A Connection has a direction.
