### ISSUE TITLE
Panning canvas

### ISSUE THREAD

**Issue by bettimms** [freegroup/draw2d#79]
Is there a built-in support for panning or any example about it?

**Comment by freegroup** [comment]
https://freegroup.github.io/draw2d/policy_selection_handling/index.html

just install the PanningPolicy in your canvas.
http://www.draw2d.org/draw2d_touch/jsdoc_6/#!/api/draw2d.policy.canvas.PanningSelectionPolicy

```
canvas.installEditPolicy(new draw2d.policy.canvas.PanningSelectionPolicy());
```

**Comment by bettimms** [comment]
Thank you for the fast reply. I've tried it already but couldn't make it work, is it possible I'm missing something else, will it conflict with any other policy or something?

**Comment by bettimms** [comment]
Consider this example. I've installed the Panning but Im not seeing it's working

https://codepen.io/bettimms/pen/RwNEJGy

**Comment by MarcoCivettini** [comment]
> Thank you for the fast reply. I've tried it already but couldn't make it work, is it possible I'm missing something else, will it conflict with any other policy or something(or maybe any specific jquery version...?)

I have the same problem.

**Comment by MarcoCivettini** [comment]
> Is there a built-in support for panning or any example about it?

To use the panningSelectionPolicy you must set the scroll area of the canvas with this method
`canvas.setScrollArea(window);`

for example if you want implement the policy in your canvas, you have to do this:

```
// create example canvas
const canvas = new draw2d.Canvas('example_canvas');
// set the scroll area with the size of the window
canvas.setScrollArea(window);
// install the panning selection policy
canvas.installEditPolicy(new draw2d.policy.canvas.PanningSelectionPolicy());
```

**Comment by bettimms** [comment]
Thank you for sharing this. Unfortunately this is not helping because if you have a `navbar` or `sidebar` or whatever, when you set scroll area `window` then it's moving everything, while you want to move/pan only let's say canvas or it's parent .

**Comment by freegroup** [comment]
you can place the canvas in any sub-DIV. It is just neccessary to declare/set the scrolling div. Without that draw2d didn't know how to calculate the offset

**Comment by freegroup** [comment]
https://codepen.io/freegroup/pen/XWbpVpW
