### ISSUE TITLE
Where is the API doc ?

### ISSUE THREAD

**Issue by dabeng** [freegroup/draw2d#8]
Hi @freegroup . I have to say that draw2d is the best js library to draw flow chart I ever met. Thank you very much for your great work 👍 

Additionally, I wonder where is the detailed tutorials or API docs ?

**Comment by justintime4tea** [comment]
The API has some documentation at:
http://www.draw2d.org/draw2d_touch/jsdoc_6/#!/api

However I'm not sure how up-to-date this is. Also there are some descrepencies I have found between the JSDOC in code (which turns into generated API docs?) and what the functions/API's really take as parameters or do. It sounds like this was recently updated and ported partially to ES6 so I suspect that might be part of the issue as well as a lot of work for one person so it's all understandable.

If things aren't working after following the docs be sure to check the functions/code itself of the library (non-minified version). 

Really liking this project and am hoping I can get some time to contribute some to it!
