### ISSUE TITLE
Readonly effect in one shape

### ISSUE THREAD

**Issue by Catublipas** [freegroup/draw2d#81]
Hello. Is it possible to apply readonly effect in only one shape? I explain, when it creates a new document it is created with a shape that is not possible to modify and select.
Is it possible?

Thanks for your help!

**Comment by freegroup** [comment]
different ways to do this.

You can set the selectionAdapter to null. Unfortunately the API didn'T allow this with a Setter.
IF you handover a Setter a default adapter is used.
```
var LabeledEnd = draw2d.shape.node.End.extend({
    
    init:function()
    {
      this._super();
    

      this.selectionAdapter = null;
    }
});
```

Or you can https://github.com/freegroup/draw2d/blob/655544563497a49832481b8060552e67ccf592f1/src/Figure.js#L2294 to false....

**Comment by Catublipas** [comment]
Thank you very much! :D

**Comment by mindfuucker** [comment]
The second 

> different ways to do this.
> 
> You can set the selectionAdapter to null. Unfortunately the API didn'T allow this with a Setter.
> IF you handover a Setter a default adapter is used.
> 
> ```
> var LabeledEnd = draw2d.shape.node.End.extend({
>     
>     init:function()
>     {
>       this._super();
>     
> 
>       this.selectionAdapter = null;
>     }
> });
> ```
> 
> Or you can
> 
> https://github.com/freegroup/draw2d/blob/655544563497a49832481b8060552e67ccf592f1/src/Figure.js#L2294
> 
> to false....

The two solutions you provided behave differently. The first one locks them in the canvas while the second still enables movement of the shape.
