### ISSUE TITLE
debugger statement in draw2d.js file

### ISSUE THREAD

**Issue by zohaibijaznbs** [freegroup/draw2d#84]
@freegroup There is debugger statement in draw2d.js file in build. It will be great if you can remove that and create a new `npm` build and publish.

Thanks :)

![image](https://user-images.githubusercontent.com/51836020/75462398-04e85680-59a6-11ea-9bf8-4601d90391cb.png)

**Comment by zohaibijaznbs** [comment]
I just searched `debugger` string and found many such occurrences in code.

**Comment by freegroup** [comment]
Hi - I need this kind of statements to track some problems in my coding. The debugger didn'T stop if you didn'T show the web-console or the error didn'T happens....which should be the default.
