### ISSUE TITLE
Allow connecting only to specific ports

### ISSUE THREAD

**Issue by akoskm** [freegroup/draw2d#85]
I want to control the ports that allow incoming connections.

![image](https://user-images.githubusercontent.com/3111627/75653256-81588f00-5c5d-11ea-9641-1069bc196cf2.png)

In the above case while I'm dragging port A I want only A1 to have visual feedback and allow connections. I don't want to allow connecting A to B1 or B.

When B is being dragged, only B1 should have visual feedback and allow connections.

Here is an older link discussing the same problem. It mentions a policy will be created in the upcoming versions to better handle these cases

https://groups.google.com/forum/#!searchin/draw2d-touch/port$20allow$20connection%7Csort:date/draw2d-touch/hFElVwlEjJI/ZuCbDI2ZHWEJ

Any updates on this? What's the recommended approach here?

**Comment by freegroup** [comment]
New Feature

https://freegroup.github.io/draw2d/index.html#/examples/port_semantic_group

https://freegroup.github.io/draw2d/index.html#/api/draw2d/port => setSemanticGroup
