### ISSUE TITLE
[BUG] selection events doesn't fire

### ISSUE THREAD

**Issue by akoskm** [freegroup/draw2d#86]
http://www.draw2d.org/draw2d_touch/jsdoc_6/#!/api/draw2d.Canvas

```
 canvas.on("select", function(emitter,event){
     if(event.figure!==null){
         alert("figure selected");
     }
     else{
         alert("selection cleared");
     }
 });
```

`"select"` event never fires when the selection is cleared.

**Comment by freegroup** [comment]
wrong API documentation. The event is splitted into `select` and `unselect` 
https://codepen.io/freegroup/pen/oNXoJGy

https://freegroup.github.io/draw2d/index.html#/api/draw2d/canvas
