### ISSUE TITLE
Hide hybrid ports

### ISSUE THREAD

**Issue by bettimms** [freegroup/draw2d#87]
Setting hybrid ports to `setVisible(false)` not hiding the ports. The idea  is to hide the ports totally on certain cases.

**Comment by freegroup** [comment]
maybe this example can help
https://freegroup.github.io/draw2d/index.html#/examples/port_hide

**Comment by bettimms** [comment]
I've looked to this example before raising the issue but didn't help. After some tests in an online editor i found that the issue seems in my project, maybe some policies conflicting or I don't know that's making the method `setVisible(false)` to not work. 
Closing it, thank you for your amazing work and support, keep it up 👍.

**Comment by bettimms** [comment]
Re-opening once again just to get any idea why when installing `canvas.installEditPolicy(new draw2d.policy.canvas.CoronaDecorationPolicy()); `setVisible(false)` on ports doesn't work?

**Comment by freegroup** [comment]
fixed with draw2d@1.0.28

**Comment by freegroup** [comment]
I add the CoronaPolicy to the demo for test purpose
https://freegroup.github.io/draw2d/index.html#/examples/port_hide
