### ISSUE TITLE
Sending figure toBack sends it behind the grid

### ISSUE THREAD

**Issue by bettimms** [freegroup/draw2d#88]
When calling `.toBack()` on a figure and the `canvas.installEditPolicy(new draw2d.policy.canvas.ShowGridEditPolicy());` is installed, figure goes behind the grid.

![image](https://user-images.githubusercontent.com/9863453/76318029-86b97780-62f6-11ea-9f0c-866f459141ca.png)

**Comment by freegroup** [comment]
already fixed with https://github.com/freegroup/draw2d/commit/2b5d632dda984387cedc3f9279ca86339d178f7a#diff-861a3889c8e4400973bff00ad506e346
