### ISSUE TITLE
How to make canvas responsive?

### ISSUE THREAD

**Issue by ucandoit1010** [freegroup/draw2d#89]
Hi everyone ! 
I need responsive canvas , but svg size always wrong.
here is my html :
`<div id="drawArea" class="col s12"><div onselectstart="javascript:/*IE8 hack*/return false" id="canvas" ></div></div>
`

and jquery :
`$("#canvas").css('width',1250); 
$("#canvas").css('height',450);`

this is the result :

![2020-03-13_09h02_24](https://user-images.githubusercontent.com/1191790/76580151-dfad2980-6509-11ea-87f4-f7842da9fcc3.png)

It doesn't work on svg width and height !
Any help would be approciated ! Thank you.

**Comment by freegroup** [comment]
Hi - the canvas isn'T responsive. You should place the canvas inside a DIV and make the div responsive.
The Canvas is the overall paint area.

**Comment by ucandoit1010** [comment]
> 
> 
> Hi - the canvas isn'T responsive. You should place the canvas inside a DIV and make the div responsive.
> The Canvas is the overall paint area.

` <div onselectstart="javascript:/*IE8 hack*/return false" id="canvas"  style="width:3000px; height:3000px;" ></div>`

**style="width:3000px; height:3000px;"**
Is width and height are required if I want to make it responsive ?

**Comment by freegroup** [comment]
```html
   <div class="content" id="draw2dCanvasWrapper">
        <div id="canvas" class="" >
        </div>
   </div>
```

check  Brainbox as example https://freegroup.github.io/brainbox/circuit/

**Comment by ucandoit1010** [comment]
> 
> 
> ```
>    <div class="content" id="draw2dCanvasWrapper">
>         <div id="canvas" class="...."  style="...">
>         </div>
>    </div>
> ```
> 
> check Brainbox as example https://freegroup.github.io/brainbox/circuit/

Ok , I will check it .
