### ISSUE TITLE
Event bubbling, drag end is actually mouse up.

### ISSUE THREAD

**Issue by gurnard** [freegroup/draw2d#90]
I have a VerticalLayout that I have extended. I use the onDragEnd function to detect a move in the shape. Within the shape I also have a label that has the on click function like this:

 on("click", (emitter, event) => {
   //run function here
});
The problem is the onDragEnd is run before the onclick on the label. The onDragEnd should not be run at all. the x and y of the shape does not change only a child element is clicked. 

How can I get the child event to run first and then prevent it bubbling up to the parent?

**Comment by gurnard** [comment]
I can replicate this changing the code pen from the docs for the vertical layout.  Clicking on the label shows the dragend alert first and the onclick second. I feel the dragend should not even be fired it is more like a mouseup than a dragend.

https://codepen.io/gurnard123/pen/eYNKmaY

**Comment by freegroup** [comment]
Hi,

works as designed.

the DragEnd event is fired because the DragStart event is fired as well.
The DragStart must be fired before a shape is moving. In this case it is not possible to avoid or cancel the DragEnd event if the shape isn't moved. I think the solution is to handle this in your shape gracefully.

Greetings

**Comment by gurnard** [comment]
But there is no drag. This is the sequence of events, draw2d does not follow this.
mousedown -> mouseup = click
mousedown -> mousemove -> mouseup = drag

The on start drag should only be triggered if the mouse moves. The lib is firing a drag on mouse down this is incorrect.
The only way I can see of fixing this bug is to do a delay on the drag event and set a flag on the click.  Or log the x and y on the dragstart and only react if different on the dragend. Either way is messy and far from graceful unless you have a better suggestion?

**Comment by freegroup** [comment]
it is not incorrect - it is how I have implement the events.

Unfortunately I can't change this behaviour because a lot of apps rely on this type of event sequence
