### ISSUE TITLE
Union in one class .VerticalLayout.extend and .SetFigure.extend

### ISSUE THREAD

**Issue by e2sence** [freegroup/draw2d#91]
Good day. is it possible to union in one class .VerticalLayout.extend and .SetFigure.extend
...
The question arose because it is impossible to draw a shadow to an object inherited from .SetFigure, and VerticalLayout has the wonderful properties needed to create collapsible shape

**Comment by freegroup** [comment]
you can apply a shadow to any kind of draw2d object....and collapsible shapes can be done with every shape...

maybe you paint a mockup of your desired shape and I try to implement a skeleton.

**Comment by e2sence** [comment]
Thank you very much, I think a similar sketch will be useful to many ) 
here's the layout
<img width="810" alt="Screenshot 2020-03-20 at 16 38 57" src="https://user-images.githubusercontent.com/32023734/77169441-8d9c7300-6aca-11ea-8ad4-51155273fcc6.png">

**Comment by e2sence** [comment]
> you can apply a shadow to any kind of draw2d object
you say, but what about SVG, how to apply a shadow to an object? can you give an example?

**Comment by freegroup** [comment]
I admit I have no example in my package of this...but i found something in the web (fraphael.js)
and I build a codepen.io example for you

https://codepen.io/freegroup/pen/LYVBKJJ

**Comment by e2sence** [comment]
you have a similar example in the distribution kit - **style_paper**...
it’s still not clear how to add a shadow to SVG, maybe there is still an opportunity to help?
<img width="598" alt="Screenshot 2020-03-21 at 13 13 18" src="https://user-images.githubusercontent.com/32023734/77224388-39e76380-6b76-11ea-95c9-69706f540fe9.png">
fraphael.js - the only option is to apply styles, shadows to draw2D objects

**Comment by freegroup** [comment]
you can'T apply shadow CSS to a svg element. You can just apply the shadow to the complete SVG.
The only why is to use a svg.filter....this is what I did in the codepen example above.

By the way....you reference to the documentation is to the deprecated version of draw2d....this is outdated and discontinued.

https://freegroup.github.io/draw2d/index.html

**Comment by e2sence** [comment]
You can just apply the shadow to the complete SVG. 

**How?**

**Comment by freegroup** [comment]
https://codepen.io/freegroup/pen/RwPBXMr

**Comment by e2sence** [comment]
ok, but what about shape created with Shape Designer
need example
please!

**Comment by freegroup** [comment]
it is always the same.....the shadow is applied to the SVG.....doesn'T matter where the shape comes from.
