### ISSUE TITLE
draw2d.command.CommandDelete Undo Error

### ISSUE THREAD

**Issue by marvz73** [freegroup/draw2d#93]
I found error in "new draw2d.command.CommandDelete" class when going to execute the undo. This error only happen if 2 Figures has a connections. 

Reproduce the issue:

1. Add to figures in canvas with 1 connection for the two figures.
2. Highlight and delete the all figures. Its uses Command to delete.
3. Execute the undo and then error "Uncaught TypeError: Cannot read property 'paper' of null"

**Comment by freegroup** [comment]
which version did you use?

this is a very, very old bug (almost 2 years ago)

**Comment by marvz73** [comment]
Im using the version draw2d@^1.0.19

**Comment by freegroup** [comment]
the current version is 1.0.32 but anyhow this kind of bug should be in your version.
How do you delete the shapes? code helps a lot
maybe you can create a codepen to reproduce this error.

https://codepen.io/freegroup/pen/ExjGQjL

**Comment by marvz73** [comment]
@freegroup 

Steps:

1. Highlight all the object in the canvas
2. Press keyboard key "Delete"
3. Press keyboard key "U"
  
Here's the sample code: https://codepen.io/marvz73/pen/dyowLWd

**Comment by freegroup** [comment]
for some reasons the keyboard didn't work on codepen in combination with a Mac
I modify your sample and add two buttons.

https://codepen.io/freegroup/pen/XWboLmG

Additional I create a deleteFunctions with works well with selections. It needs a little bit
of logic inside. Maybe I modify the CommandDelete operation to support selection deletion
out of the box.

**Comment by marvz73** [comment]
Yeah, It would be much better if this logic is already inside that command. So other wont encounter similar to this issue. 

Thanks for the answer.

**Comment by freegroup** [comment]
thats good..I will do this in the far future
