### ISSUE TITLE
Removing output ports and adding new ones results in UI glitch

### ISSUE THREAD

**Issue by feraswilson** [freegroup/draw2d#95]
Hi,

I’m trying to remove outgoing ports for a Between node and then trying to add new ones. When I do that glitch happens were port circle is positioned almost in the middle of a node, but then when I move the node then it goes back into the right place.

My code:
this.getOutputPorts.each(e => removePort(e))
this.createPort(“output”)

Why is this happening?
Thanks

**Comment by marvz73** [comment]
@feraswilson 

Try like this this.getOutputPorts.each( (i, e)=> removePort(e) ) because the first params of each loop is index.

**Comment by freegroup** [comment]
addition you shoud call "layoutPorts" this doen by the framework if you add the shape to the canvas.
If the shape already part of the canvas, the call is missed (seems to be a bug)

see: https://codepen.io/freegroup/pen/zYGVzXa

**Comment by feraswilson** [comment]
@marvz73 I was just showing psuedo code. Excuse me for not being very clear.

@freegroup That did it! Thanks a lot. 

I will use this (this.layoutPorts()) temporarily until the issue is fixed. This is what I am doing, so it can give you a better understanding of where I am using it and how you could solve it in the best way:
https://github.com/dopplertask/doppler/blob/075a4eee777fb1e7724450df05e60c3a2dbe7f12/backend/src/main/resources/static/js/common/SwitchAction.js#L69

I call updatePorts from the outside. Good luck!
