### ISSUE TITLE
HTML and CSS inside label

### ISSUE THREAD

**Issue by feraswilson** [freegroup/draw2d#96]
Hi,

Is there a way to add fontawesome icons into the nodes? Like <i class=“fa fa-glass”></i>

Thanks

**Comment by freegroup** [comment]
no.

Font awesome is HTML and Draw2d is pure SVG/Canvas. Sorry for that

**Comment by freegroup** [comment]
I did something similar...but has a lot of limitations
http://www.brainbox-demo.de/circuit/?global=/basic/counter/BCDCounter-JK-7Segment.brain

The text box above the diagram is markdown. You can add even MathML in the box.
